### ISSUE TITLE
Missing properties group and subgroup for all regional indicators?

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#143]
Hi @milesj! 

I would have expected that every emoji listed in `/emojibase-data/en/data.json` has a property for group and subgroup. But all  regional indicators seems to be lacking those e.g. 

```json
{"label":"regional indicator A","hexcode":"1F1E6","emoji":"🇦","text":"","type":1,"version":0}
```

I'm wondering whether this is a bug or it is on purpose. Please confirm.

We are about to release OpenMoji 14.0 ... and the regional indicators were the very last ones which we designed, hence I stumbled upon this potential inconsistency. 

Many thanks for all your effort maintaining emojibase! 🙏

**Comment by milesj** [comment]
@b-g This is on purpose. Regional indicators are component/modifier emojis, not emojis, so they do not "show up" and are typically not usable by users. They originally were not in the dataset at all, but I added them since they are popular.

However, the groups/subgroups are based on the official unicode dataset, which you can see here: https://unicode.org/emoji/charts/full-emoji-list.html I have no plans to add custom groups to this list, so right now, regional indicators are basically ungrouped.

**Comment by b-g** [comment]
Many thanks for the clarification! Understood and makes sense. Closed.
