### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by LosTigeros** [milesj/emojibase#19]
I can't find any details about these emojis:
![image](https://user-images.githubusercontent.com/6253928/45354822-f7c38600-b5be-11e8-8669-d6f5d27588e7.png)

**Comment by milesj** [comment]
@LosTigeros Because most of these aren't real emojis.

* A-Z are regional indicators and are used to create flag emojis. They aren't stand alone emojis. https://emojipedia.org/regional-indicator-symbol-letter-a/
* Skin tones are used as modifiers. They aren't stand alone emojis. https://emojipedia.org/emoji-modifier-fitzpatrick-type-1-2/
* Skier skin tones are not supported. https://emojipedia.org/skier-type-3/
* 109 Shibuya isn't supported. https://emojipedia.org/shibuya/

However, i'll look into the following.

* Eye speech bubble. https://emojipedia.org/eye-in-speech-bubble/
* Man/Woman in tuxedo. https://emojipedia.org/man-in-tuxedo/
* Levitating suit skin tones. https://emojipedia.org/man-in-business-suit-levitating/

**Comment by milesj** [comment]
Those 3 emojis at the bottom do exist in the datasets. Gonna close this now.

**Comment by ZerataX** [comment]
I personally think regional indicators should be considered emoji, but I understand that this isn't so clear cut.


They have both `Emoji=Yes` and `Emoji_Presentation=Yes`,

but they also do have `Emoji_Component=Yes`
But I don't think that this necessarily precludes them from usage. Previously linked emojipedia also does **not** list A-Z regional indicators as non RGI. 

and most importantly most other vendors seem to use them as emoji. 

I personally use the [element](https://github.com/vector-im/element-web) messenger, which uses this library and now seems incomplete in comparison to e.g. discord.

**Comment by milesj** [comment]
@ZerataX Yeah a lot has changed in the last 2 years. Open to including them in the next major.

**Comment by milesj** [comment]
@ZerataX Looked into this. Since these emojis should be hidden from the consumer, none of them have localized annotations/tags/etc to use, which results in all these datasets being incorrect. This turned out to... not be an easy change.

**Comment by milesj** [comment]
Messing around with it here: https://github.com/milesj/emojibase/pull/66

**Comment by ZerataX** [comment]
ah wow looks great!

**Comment by LosTigeros** [comment]
Aye! That's a good change 👍
