### ISSUE TITLE
Flags are missing demonym tags

### ISSUE THREAD

**Issue by nolanlawson** [milesj/emojibase#75]
First off, thank you for making `emojibase`. It is an incredible library that simplifies so many aspects of creating emoji pickers and emoji search databases. My project [emoji-picker-element](https://github.com/nolanlawson/emoji-picker-element) would not have been possible without it. I wouldn't have even attempted it if `emojibase` did not exist. So thank you! :slightly_smiling_face:

I noticed that, in English, the flag emoji tags/annotations do not include demonyms. So for instance:

- "Denmark" :heavy_check_mark: / "Danish" :x: 
- "Ireland" :heavy_check_mark: / "Irish" :x:
- "England" :heavy_check_mark: / "English" :x:

You can test this by searching for e.g. ["english"](https://emojibase.dev/shortcodes?filter=english) or ["danish"](https://emojibase.dev/shortcodes?filter=danish) on emojibase.dev.

I understand if it's the responsibility of `emojibase` users to do stemming/expansion/etc. E.g. the :pray: emoji has keywords for `pray`, but not `praying` (nor `prays`, `prayer`, other conjugations, etc.). Totally understandable, especially for languages with tons of conjugations. Just wanted to raise the issue in case it's of interest. Thanks! :slightly_smiling_face: 

Related: https://github.com/nolanlawson/emoji-picker-element/issues/11

**Comment by milesj** [comment]
@nolanlawson Thanks for the report, but unfortunately, this is something most likely out of my control. All the tags in emojibase are based on the official Unicode CLDR, as I do not maintain them myself, and unless CLDR adds support for it, it'll probably never happen.

The CLDR tags can be found here: https://github.com/unicode-org/cldr/blob/master/common/annotationsDerived/en.xml#L3609
I also add the country code manually since it's the combination of the regional indicator emoji characters: https://github.com/milesj/emojibase/blob/master/packages/generator/src/builders/buildAnnotationData.ts#L119

**Comment by nolanlawson** [comment]
Thanks for the explanation! Just wanted to put it on your radar, but totally understand that it's out of your control. Looks like maybe this should be an upstream issue in the Unicode CLDR. Closing for now, no worries.

**Comment by milesj** [comment]
@nolanlawson Sorry I couldn't be of more help. But I definitely agree this would be nice to have. Not sure where to request this in regards to CLDR though.
